### PR TITLE
WCMS-492 mismatch issue fix for external article and article authors

### PR DESCRIPTION
**Pull request by rift137**

### CODE REVIEW

**Comment by rift137** [comment]
@halloffame do you mind pulling this down and testing it to see if it fixes the error you were getting?

**Comment by halloffame** [comment]
Let me try writing some test cases for the situation this should be fixing.

**Comment by halloffame** [comment]
Just as a note, since we are changing method names, this could potentially break things in the apps that are using this gem. We might consider doing a major version bump or just be careful when updating.

**Comment by rift137** [comment]
:+1:

**Pull request merged**
